INSERT INTO brands ( name ) VALUES ('Kanu' );
INSERT INTO brands ( name ) VALUES ('Agility' );
INSERT INTO brands ( name ) VALUES ('My Pet' );
INSERT INTO brands ( name ) VALUES ('Loving Pets' );
INSERT INTO brands ( name ) VALUES ('Tre Ponti' );
INSERT INTO brands ( name ) VALUES ('Kong' );
INSERT INTO brands ( name ) VALUES ('Evolve' );
INSERT INTO brands ( name ) VALUES ('Carval' );
INSERT INTO brands ( name ) VALUES ('Vetnil' );
INSERT INTO brands ( name ) VALUES ('Elanco' );
INSERT INTO brands ( name ) VALUES ('Natural Freshly' );
INSERT INTO brands ( name ) VALUES ('Dinky' );
INSERT INTO brands ( name ) VALUES ('Hills' );
INSERT INTO brands ( name ) VALUES ('Royal Canin' );
INSERT INTO brands ( name ) VALUES ('Total Max' );
INSERT INTO brands ( name ) VALUES ( 'Nutrecan');
INSERT INTO brands ( name ) VALUES ('Pedigree' );
INSERT INTO brands ( name ) VALUES ('Whiskas' );
INSERT INTO brands ( name ) VALUES ('Dog Chow' );
INSERT INTO category ( name ) VALUES ('Perros');
INSERT INTO category ( name ) VALUES ('Gatos');
INSERT INTO category ( name ) VALUES ('Alimentos');
INSERT INTO category ( name ) VALUES ('Accesorios');
INSERT INTO category ( name ) VALUES ('Snacks');
INSERT INTO category ( name ) VALUES ('Juguetes');
INSERT INTO category ( name ) VALUES ('Medicamentos');
INSERT INTO category ( name ) VALUES ('Higiene y belleza');
INSERT INTO rol ( name ) VALUES ('Usuario');
INSERT INTO rol ( name ) VALUES ('Administrador');
INSERT INTO rol ( name ) VALUES ('Visitante');
INSERT INTO users ( name, lastname, email, password, cellphone, address, image,idRol) VALUES ('Luisa','Escobar','lui.fer@gmail.com','luisaFda16*',123456789,'Carrera3 # 18- 45','Luisa.jpeg',1);
INSERT INTO users ( name, lastname, email, password, cellphone, address, image,idRol) VALUES ('Alejandro','Londoño','sweekly1@rediff.com','gmuQ57HNsZzz0*',123456789,'Carrera 7 # 84- 72','user_2.jpg',1);
INSERT INTO users ( name, lastname, email, password, cellphone, address, image,idRol) VALUES ('Luis','Cortes','aetteridge2@gnu.org','ZAWWERDmd987*',123456789,'Calle 11 No. 4 - 14','user_3.jpg',1);
INSERT INTO users ( name, lastname, email, password, cellphone, address, image,idRol) VALUES ('Will','Butchers','wbutchers3@blogspot.com','qvtmUBRu*87',123456789,'Carrera 7 # 84- 72','user_4.jpg',3);
INSERT INTO users ( name, lastname, email, password, cellphone, address, image,idRol) VALUES ('Kai','Assel','kassel4@disqus.com','I917VT8uPXI*54',123456789,'Calle 11 No. 4 - 14','user_5.jpg',2);
INSERT INTO users ( name, lastname, email, password, cellphone, address, image,idRol) VALUES ('Stephen','Wey','swey5@seattletimes.com','JnUycrZ*987',123456789,'Calle 10 No. 5-22','user_6.jpg',1);
INSERT INTO users ( name, lastname, email, password, cellphone, address, image,idRol) VALUES ('Katey','McInerney','kmcinerney6@hugedomains.com','r4vNVI*45',123456789,'Calle 10 No. 5-22','user_7.jpg',1);
INSERT INTO users ( name, lastname, email, password, cellphone, address, image,idRol) VALUES ('Pearla','Krebs','pkrebs7@gov.uk','28ZkTOMgj5#',123456789,'Carrera 7 # 84- 72','user_8.jpg',2);
INSERT INTO users ( name, lastname, email, password, cellphone, address, image,idRol) VALUES ('Hortensia','Harby','hharby8@about.com','8MAevZ4KN#',123456789,'Calle 10 No. 6-22','user_9.jpg',1);
INSERT INTO users ( name, lastname, email, password, cellphone, address, image,idRol) VALUES ('Franni','Schechter','fschechter9@people.com.cn','2bHw2hufj*',123456789,'Calle 10 No. 5-25','user_10.jpg',3);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Alimento Para Perro Adulto Premium Pollo', 50000,'product1.webp',10,'Max Premium Especial Pollo & Vegetales contiene proteínas de alta calidad. Su fórmula está enriquecida con vitaminas y minerales que le darán a tu amigo de cuatro patas la energía necesaria para disfrutar al máximo la mejor etapa de su vida. Variedad de ingredientes y nutrición balanceada que harán feliz a tu perro con cada bocado.',15);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Alimento Para Perro Pollo y Vegetales - Raza Pequeña',30000,'product2.webp',20,'Ideal para razas pequeñas por el tamaño de la croqueta, alimento indicado para perros adultos de razas pequeñas con pollo, vegetales, arroz y maíz, extracto de Yucca Shidigera para la reducción del olor de las heces.',15);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Alimento Para Perro - Hills Perfect Digestion',80000,'product3.webp',15,'Ayuda al cuerpo de tu mascota a absorber y utilizar nutrientes vitales.',13);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Alimento Para Perro - Royal Canin Chihuahua Senior 8',60000,'product4.webp',3,' incluye un complejo de nutrientes para apoyar a los chihuahuas envejecidos. Contiene una combinación exclusiva de antioxidantes para ayudar a mantener la salud celular y está formulado con un contenido de fósforo adecuado para perros mayores.',14);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Alimento Para Gato - Royal Canin Mother And Baby Cat',13000,'product5.webp',6,'El alimento húmedo para gatos Mother & Baby Cat está formulado para satisfacer las necesidades específicas de los gatitos en crecimiento (de 1 a 4 meses) y las gatas embarazadas o lactantes.',14);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Alimento Para Gato - Evolve Libre de Granos Pavo 85 Gr',7000,'product6.webp',10,'Los exclusivos Pouches Evolve Grain Free para Gatos están hechos con CARNE REAL y con los mejores ingredientes junto con carbohidratos saludables SIN GRANOS y superalimentos como arándanos, arándanos agrios y más. ',7);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Alimento Para Gato - Agility Gold Esterilizados',30000,'product7.webp',18,'- Movilización de grasas. - Reducción calórica. - Control de bolas de pelo. - Favorece la salud renal.',2);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Alimento para gato -Hills Felino K/D 4 Lb',65000,'product8.webp',2,'Protege la función del riñón y el corazón de vital importancia. Es compatible con la capacidad natural del gato para aumentar la masa muscular diaria. Estimula el apetito y aumenta el consumo de calorías.',13);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Arnes Primo Militar Para Perro',150000,'product9.webp',8,' Talla XL ideal para perros de 30 a 40 KG. - Medidas de contorno 76 cm min/97 cm max. - Adecuado para perros medianos y grandes; material hipoalergénico, impermeable, duradero y fabricado en Italia. Su diseño único y ergonómico lo hace totalmente cómodo.',5);
INSERT INTO products ( name, price, image, amount, description, color, idBrand) VALUES ('Laberinto Para Gato',105000,'product10.webp',1,'Producto bajo revisión de inventario, tiempo estimado de entrega de 5 a 8 días hábiles. - Juguete inteligente que estimula a los gatos a trabajar por su comida. - Con 6 actividades divertidas.','Blanco y verde',6);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Galletas Natural Value Potato And Chicken Para Perro',11100,'product11.webp',11,'Tu mascota anhelará estos bocadillos CRUJIENTES y deliciosos Con MENOS DE 10 CALORIAS por bocadillo, son el bocadillo de entrenamiento perfecto o un bocadillo para cualquier momento. No contienen maíz, soja ni glicerina. Estas golosinas crujientes son perfectas para perros de cualquier edad o tamaño.',4);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Galletas Kanu Hairball Control Para Gato',7500,'product12.webp',12,' Cada bocado tiene un tamaño aproximado de 8mm x 1,3cm. Para Kanú es vital brindarle a nuestras mascotas no solo sabor sino también nutrición. Nuestro Snack Kanú Hairball Control es un delicioso alimento complementario a base de ingredientes 100% naturales como el extracto de malta, carne, levadura y más, que ayudan a controlar las molestas bolas de pelos.',1);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES (' Peluche Roughskin Mico Medium Para Perro',63000,'product13.webp',5,'KONG RoughSkinz Suedez están diseñados para brindar durabilidad al mismo tiempo que recompensan el comportamiento de masticación adecuado y brindan una diversión duradera.',6);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Catit Senses 2.0 Circuito de Juego Para Gato',94800,'product14.webp',7,'Producto bajo revisión de inventario, tiempo estimado de entrega de 5 a 8 días hábiles. Incluye el circuito de 5 tramos, 2 piezas de cierre y 1 pelota. ',6);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Ciclorac X 120 Ml para todas',26500,'product15.webp',9,'Ciclorac elimina el 99,9% de la carga microbiana. Fórmula incolora que no mancha la piel de las mascotas. No requiere enjuague. Para el tratamiento de cualquier tipo de heridas crónicas y complejas con y sin infección asociada. NO causa daño en piel y tejidos. ',8);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Organew Para Todas',19600,'product16.webp',12,'Suplemento nutricional que tiene aminoácidos , vitaminas , probióticos y prebióticos , para la reposición de la flora gastro intestinal.',9);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Dinky Spray Para Peinar Con Argan Mascotas',44300,'product17.webp',21,'Con la sofisticada fórmula de nuestro nuevo Spray Brillo y Reparación con Argán, reduce la resequedad de la piel de tu #AmigoFiel, recuperando el brillo sensacional de su pelaje y previniendo su envejecimiento, además ¡Te deleitarás con su exquisita fragancia!',12);
INSERT INTO products ( name, price, image, amount, description, idBrand) VALUES ('Perfume Para Machos Esbelt para todos',25900,'product18.webp',13,'El agradable Perfume para Machos permite que su mascota tenga un delicioso aroma. Con Aloe vera, Romero, Hamamelis.',11);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (1,1);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (1,3);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (2,1);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (2,3);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (3,1);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (3,3);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (4,1);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (4,3);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (5,2);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (5,3);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (6,2);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (6,3);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (7,2);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (7,3);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (8,2);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (8,3);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (9,1);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (9,4);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (10,2);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (10,4);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (11,1);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (11,5);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (12,2);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (12,5);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (13,1);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (13,6);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (14,2);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (14,6);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (15,1);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (15,2);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (15,7);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (16,1);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (16,2);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (16,7);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (17,1);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (17,2);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (17,8);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (18,1);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (18,2);
INSERT INTO categoryproducts ( idProduct,idCategory) VALUES (18,8);
INSERT INTO cart ( totalPrice,amount,date,idUser) VALUES (160000,3,'2022-02-01',1);
INSERT INTO cart ( totalPrice,amount,date,idUser) VALUES (110000,4,'2022-02-07',2);
INSERT INTO cart ( totalPrice,amount,date,idUser) VALUES (215000,2,'2022-02-12',3);
INSERT INTO cart ( totalPrice,amount,date,idUser) VALUES (105000,1,'2022-02-12',1);
INSERT INTO cart ( totalPrice,amount,date,idUser) VALUES (202900,5,'2022-02-19',6);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (1,1);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (2,1);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (3,1);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (4,2);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (5,2);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (6,2);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (7,2);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (8,3);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (9,3);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (10,4);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (11,5);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (12,5);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (13,5);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (14,5);
INSERT INTO cartProducts ( idProducts,idCart) VALUES (15,5);

